Readme
xaptum/xaptum-buildroot pull request #176
Opened 2020-10-14 23:14 UTC by dberliner

This contains two unrelated changes. I've revised the documentation and removed `xaprc-eval-tool` from default builds. Unless I'm mistaken the entire project was made obsolete by `xaprc-control` so complete removal may be a good idea.

2020-10-15 16:15 UTC, drbild requested changes
Just the one  questions about removing the documentation for building in multiple directories.  I think we want to keep that, but perhaps revised to fix the out-of-date defconfig names.

2020-10-15 16:16 UTC, dberliner commented on README.md
> -Use separate build directories to simplify working with multiple
Yeah, I'll add that back.

2020-10-21 19:54 UTC, drbild requested changes

2020-10-21 19:54 UTC, drbild commented on README.md
> -make O=$PWD -C ../.. sama5d2_xplained_xaprc_defconfig
Can you keep the example code, up to this line?  I refer back to it for the correct syntax for initializing the defconfig from a separate build directory.  (The `make -O=$PWD -C ../.. <defconfig>` syntax).

2020-10-21 19:56 UTC, drbild approved these changes
Once that `make -O=$PWD -C ../.. <defconfig>` line is added back, LGTM.

2020-10-21 20:06 UTC, merged